version: "2"
services:
  builder:
    image: openlmis/dev:5.2
    links:
      - log
    volumes:
      - '.:/app'
      - '../logback.xml:/logback.xml'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    env_file: .env
  image:
    build: .
    image: openlmisao/service-desk
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/service-desk:/var/log'
